### PR TITLE
centos8 firewalld - add required ports

### PR DESCRIPTION
**Pull request by shwstppr**
Stop and disable firewalld on mgmt

### CODE REVIEW

**Comment by shwstppr** [comment]
@andrijapanicsb @vladimirpetrov please check

**Comment by andrijapanicsb** [comment]
It's better to spin a test Jenkins job, using this custom Trillian branch (check Reference Trillian job) - and check if it was stopped once the env is built.

**Comment by shwstppr** [comment]
@andrijapanicsb did that acs-pr-trillian 2194

**Comment by PaulAngus** [comment]
I don't think that we should be disabling firewalls, no one is going to do that in production.  We should know the required ports and only open those ports.

**Comment by shwstppr** [comment]
Added specific ports 3306, 8080, 8096, 8250, 8443 and 9090.
Initially I added disabling firewalld because on current master of Trillian, firewalld remains in stopped state when env is first started but somehow systemd starts it once the host is rebooted.
Anyway, this works fine now. Tested with http://10.10.4.61:8080/client/

**Comment by andrijapanicsb** [comment]
Assuming ssh access is enabled by default (afaik), LGTM

@shwstppr shouldn't we do the exact same stuff on centos7 mgmt?

**Comment by shwstppr** [comment]
@andrijapanicsb for some reasons lab's centos7 template doesn't have firewalld installed,

From a running environment,
```
⇒  ssh root@10.10.3.192                                              
root@10.10.3.192's password: 
Last login: Mon Jul 27 10:29:09 2020 from 10.1.0.1
[root@ref-trl-1287-v-M7-abhishek-kumar-mgmt1 ~]# hostnamectl
   Static hostname: n/a
Transient hostname: ref-trl-1287-v-M7-abhishek-kumar-mgmt1
         Icon name: computer-vm
           Chassis: vm
        Machine ID: 76b17df4966743ce9a20fe9a7098e2b6
           Boot ID: 1781a038a36c47c0b8212865de16fee6
    Virtualization: vmware
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-957.12.2.el7.x86_64
      Architecture: x86-64
[root@ref-trl-1287-v-M7-abhishek-kumar-mgmt1 ~]# systemctl status firewalld
Unit firewalld.service could not be found.
```

**Comment by andrijapanicsb** [comment]
ok, looks like an inconsistent template build - but is OK anyway

**Pull request merged**
