### PR TITLE
Install specific mysql-connector-python version

### PR DESCRIPTION
**Pull request by vishesh92**

### CODE REVIEW

**Comment by weizhouapache** [comment]
we do have specified the version 

https://github.com/shapeblue/Trillian/blob/50a6d990aca9d7fc7c97e5a9efba9efab59f0421/Ansible/roles/marvin/tasks/install_marvin_prereqs.yml#L140

I have no idea why it is not working now ...

@vishesh92 
have you kicked a trillian test with this branch ?

**Comment by vishesh92** [comment]
Just launched an environment. Once it's up I will manually run the test to verify.

On installing cloudstack-marvin package, mysql-connector-python version gets upgraded to 8.0.30. So, this PR installs 8.0.29 version after cloudstack-marvin package installation to reset the version back to 8.0.29.

**Comment by weizhouapache** [comment]
alternatively, can we downgrade the version to 8.0.29 ?

tools/marvin/setup.py:          "mysql-connector-python <= 8.0.30",

**Comment by vishesh92** [comment]
> alternatively, can we downgrade the version to 8.0.29 ?
> 
> tools/marvin/setup.py:          "mysql-connector-python <= 8.0.30",
> 

Yes. That should also work. Haven't tested that yet. Since this is specific to mariadb only, I have made the changes here.

**Pull request merged**
