### PR TITLE
add el9 support

### PR DESCRIPTION
**Pull request by shwstppr**
Adds support for:

- Oracle Linux 9.0
- Alma Linux 9.0

Test with AlmaLinux 9.0

http://sl-jenkins-master.sofia.shapeblue.com:8080/job/Reference_Trillian/4271/console

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@shwstppr , I see some licenses missing. Pretty sure this is not as much of an issue as with apache projects, but want to make sure this is not a mistake.

**Comment by shwstppr** [comment]
@DaanHoogland thanks for pointing out. Will check and update

**Review by rohityadavcloud — APPROVED** [review]
LGTM - could you get a review from Andrija/Lucian and David @shwstppr. As far as I'm concerned,  if it works in Lab then LGTM.

**Review by NuxRo — APPROVED** [review]
LGTM

**Pull request merged**
