### PR TITLE
fix test_data for vapps tests

### PR DESCRIPTION
**Pull request by shwstppr**
Adds test data for vApps tests (test_vm_life_cycle.py).

### CODE REVIEW

**Comment by shwstppr** [comment]
@nvazquez vApps tests in `test_vm_life_cycle.py` were failing on Trillian as test_data was not having the required details.
```
2021-03-10 01:17:30,654 - CRITICAL - EXCEPTION: test_01_unmanage_vm_cycle: ['Traceback (most recent call last):\n', '  File "/usr/lib/python2.7/site-packages/nose/suite.py", line 209, in run\n    self.setUp()\n', '  File "/usr/lib/python2.7/site-packages/nose/suite.py", line 292, in setUp\n    self.setupContext(ancestor)\n', '  File "/usr/lib/python2.7/site-packages/nose/suite.py", line 315, in setupContext\n    try_run(context, names)\n', '  File "/usr/lib/python2.7/site-packages/nose/util.py", line 471, in try_run\n    return func()\n', '  File "/marvin/tests/smoke/test_vm_life_cycle.py", line 1752, in setUpClass\n    cls.services[\'test_ovf_templates\'],\n', "KeyError: 'test_ovf_templates'\n"]
```

I added the changes and have copied http://10.2.0.4/marvin/machina-2dd-iso.ova from http://10.5.1.128/templates/machina-2dd-iso.ova.

```
2021-03-10 08:28:35,071 - CRITICAL - EXCEPTION: None: ['Traceback (most recent call last):\n', '  File "/usr/lib/python2.7/site-packages/nose/suite.py", line 209, in run\n    self.setUp()\n', '  File "/usr/lib/python2.7/site-packages/nose/suite.py", line 292, in setUp\n    self.setupContext(ancestor)\n', '  File "/usr/lib/python2.7/site-packages/nose/suite.py", line 315, in setupContext\n    try_run(context, names)\n', '  File "/usr/lib/python2.7/site-packages/nose/util.py", line 471, in try_run\n    return func()\n', '  File "/marvin/tests/smoke/atest.py", line 97, in setUpClass\n    assert False, "get_test_ovf_templates() failed to return templates"\n', 'AssertionError: get_test_ovf_templates() failed to return templates\n']
```

Can you please check if the OVF template is correct or do we need to change `get_test_ovf_templates` method.

PS: Before https://github.com/shapeblue/Trillian/commit/bf597e5a1ca6784ab0065cfb1bc4be1615dbc2d5 Trillian was having a different version of `test_vm_life_cycle.py`

**Comment by rhtyd** [comment]
@shwstppr is this ready for merging? cc @Pearl1594 @davidjumani

**Comment by shwstppr** [comment]
@rhtyd I think issue is not there on Sofia lab. I'll check and reopen (with changes) if needed.

**Comment by shwstppr** [comment]
Verified issue is still there.
While this fixes the failing tests, @nvazquez need to verify template to be used, https://github.com/shapeblue/Trillian/pull/128/files#diff-27fd2cc7d23dbc532fb65312275e4dbb61bec62418aa849ecaa82296f2d40c51R1020

**Comment by rhtyd** [comment]
@shwstppr can you check your branch - does it need rebasing, there are many additional commits than your change

**Comment by nvazquez** [comment]
Thanks @shwstppr, I've copied the .ova from '10.0.3.122/other_templates' to '10.0.3.122/marvin/' and placed your code on a marvin box '/marvin/test_data.py' file.

**Comment by nvazquez** [comment]
Ne

**Review by borisstoyanov — APPROVED** [review]

**Comment by nvazquez** [comment]
@shwstppr we might consider rebasing the branch `vmware-sofia-lab` instead of `sofia-lab`

**Pull request merged**
