### PR TITLE
Set local repo for centos7 / el7 hosts in trillion env (for MS, KVM, Marvin box)

### PR DESCRIPTION
**Pull request by sureshanaparti**
Set local repo for centos7 / el7 hosts in trillion env (for MS, KVM, Marvin box)

This PR fixes repo in centos7 / el7 hosts in trillion env, points to local repo - http://10.0.3.121/centos/7/ instead of http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock.

Existing group var _os_repo_ used for the base url.

Tested with below env in lab.
[http://sl-jenkins-master.sofia.shapeblue.com:8080/job/acs-pr-trillian/10716/console]

```
pr9323-t10716-kvm-centos7-suresh.anaparti
pr9323-t10716-kvm-centos7   02/07/24 16:06    PR Link   state: Running smoke tests   ❚❚  ►   Jenkins  Primate View   Teardown
pr9323-t10716-kvm-centos7-mgmt1	10.0.32.119	Up   UI SSLUI SFTP SSH
pr9323-t10716-kvm-centos7-kvm2	10.0.32.253	Up   SFTP SSH
pr9323-t10716-kvm-centos7-kvm1	10.0.34.190	Up   SFTP SSH
pr9323-t10716-kvm-centos7-marvin	10.0.112.221	Up   SFTP SSH
pr9323-t10716-kvm-centos7-mgmt2	10.0.34.194	Up   SFTP SSH CPVM: Up, SSVM: Up
```

### CODE REVIEW

**Comment by sureshanaparti** [comment]
@rohityadavcloud  @borisstoyanov @vladimirpetrov @kiranchavala @DaanHoogland @NuxRo @weizhouapache @shwstppr Please review and advise. Thanks.

**Comment by sureshanaparti** [comment]
ansible template module fails to set the local repos from the template files as `libselinux-python` was not available (and cannot be installed as the repos are unreachable), so local repo is set using shell cmd (same as the repo template file) in MS, KVM and Marvin Box - all CentOS7/EL7 hosts.

**Comment by weizhouapache** [comment]
thanks @sureshanaparti 

it may be better to create some template files (.j2)

**Comment by sureshanaparti** [comment]
> thanks @sureshanaparti
> 
> it may be better to create some template files (.j2)

@weizhouapache there are template files already, but seting the local repo with them using ansible template module is failing (seems they have some dependency with `libselinux-python`)

**Review by rohityadavcloud — APPROVED** [review]
LGTM didn't test it

**Review by borisstoyanov — APPROVED** [review]
LGTM

**Pull request merged**
