### PR TITLE
Update test data 

### PR DESCRIPTION
**Pull request by borisstoyanov**
sync test data with community and add missing attribute for 'templateregister' item

### CODE REVIEW

**Comment by borisstoyanov** [comment]
@PaulAngus Ok with merging this?

**Comment by rhtyd** [comment]
LGTM @borisstoyanov please merge if it helps with new/existing tests. Given it's been close to 2 weeks, please re-sync if necessary. I've rebased and fixed your branch.

**Comment by borisstoyanov** [comment]
@rhtyd I'm not authorized to merge in this repo, I don't see any changes in the community test_data since my change: https://github.com/apache/cloudstack/commits/812c56b5e3574566de92de137671e7ccc98e86df/tools/marvin/marvin/config/test_data.py

**Comment by DagSonsteboSB** [comment]
@borisstoyanov @rhtyd merged.

**Pull request merged**
