### PR TITLE
Adding a nfs2 hardcoded entry in Trillian's test_data.py in order to …

### PR DESCRIPTION
**Pull request by borisstoyanov**
…pass newly introduced test in https://github.com/apache/cloudstack/pull/1961

### CODE REVIEW

**Comment by PaulAngus** [comment]
this path is not valid. - we use paths which include the environment name so that they are unique
url of OUR storage shouldn't be hard coded into Trillian code - use variable 
additional storage location must be added to storage before it can be used.

**Comment by borisstoyanov** [comment]
Thanks @PaulAngus, that makes sense. I guess I'll need to add task to create and delete the directory in the cloudstack-nfsshares/tasks/main.yml ?

**Comment by borisstoyanov** [comment]
@PaulAngus can you look at this and comment if you're happy with this change so we could merge it or review it. There's a  newly added test in the smoketests which is failing because of missing this.

**Comment by borisstoyanov** [comment]
tests are passing as well:

```
[root@ref-trl-99-k-cs410-bstoyanov-marvin ~]# cat /marvin//MarvinLogs/test_snapshots_76YGPX/results.txt
Test Snapshot Root Disk ... === TestName: test_01_snapshot_root_disk | Status : SUCCESS ===
ok
Test listing volume snapshots with removed data stores ... === TestName: test_02_list_snapshots_with_removed_data_store | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 2 tests in 216.488s

OK
```

**Comment by PaulAngus** [comment]
it makes no functional difference, but you can make it neater by doing:

- name: Create subfolders
  file: state=directory path={{ env_pripath }}{{ env_name_clean }}/{{ item }} mode=0755
  with_items:
    - "marvin_pri1"
    - "nfs2"
  when: build_marvin

**Comment by PaulAngus** [comment]
formatting made - into a circle 
bitmoji

**Comment by PaulAngus** [comment]
`- name: Create subfolders
  file: state=directory path={{ env_pripath }}{{ env_name_clean }}/{{ item }} mode=0755
  with_items:
    - "marvin_pri1"
    - "nfs2"
  when: build_marvin`

**Comment by PaulAngus** [comment]
grrr

**Comment by borisstoyanov** [comment]
I've added the requested changes, deployed an environment and tests are looking good.
```
[root@ref-trl-100-k-cs410-bstoyanov-marvin ~]# cat /marvin//MarvinLogs/test_snapshots_4U1I5D/results.txt
Test Snapshot Root Disk ... === TestName: test_01_snapshot_root_disk | Status : SUCCESS ===
ok
Test listing volume snapshots with removed data stores ... === TestName: test_02_list_snapshots_with_removed_data_store | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 2 tests in 630.004s

OK
```
Should we proceed with merging this now?

**Comment by DagSonsteboSB** [comment]
LGTM Bobby.

**Comment by borisstoyanov** [comment]
Thanks for the change @DagSonsteboSB I've tested it and it works as expected now, it's skipping pool creation when it has to. Tests look good as well:
```
[root@ref-trl-104-k-cs410-bstoyanov-marvin ~]# cat /marvin//MarvinLogs/test_snapshots_6ZZRSL/results.txt
Test Snapshot Root Disk ... === TestName: test_01_snapshot_root_disk | Status : SUCCESS ===
ok
Test listing volume snapshots with removed data stores ... === TestName: test_02_list_snapshots_with_removed_data_store | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 2 tests in 224.234s

OK
```

**Comment by DagSonsteboSB** [comment]
LGTM:

root@SBLabNestedNFS ref-trl-104-k-cs410-bstoyanov]# tree
.
├── 98c91cc6-8ad7-4158-86ea-3b8995417cd2
├── marvin_pri1
├── nfs2
│   └── KVMHA
│       └── hb-10.2.2.42
└── ref-trl-104-k-cs410-bstoyanov-kvm-pri1
    ├── 9cb8b3ee-d707-45fb-a924-c328f508eebe
    ├── 9db295e4-d9a3-4cba-9b54-a8dd34a668fa
    ├── a13f25bc-fadf-4748-9ddc-17811af714ad
    └── KVMHA
        └── hb-10.2.2.42

**Pull request merged**
